### ISSUE TITLE
Does not work with simple Scroll View

### ISSUE THREAD

**Issue by rohan90** [makovkastar/FloatingActionButton#198]
I tried your lib, i see the fab in the preview [ so obviously my layout is correct]
I get the exception upon opening the fragment view.

<code>
  Caused by: java.lang.ClassCastException: android.widget.ScrollView cannot be cast to com.melnykov.fab.ObservableScrollView
            at com.prontoitlabs.hunter.activity.AddJobsActivity.initFAB(AddJobsActivity.java:113)
            at com.prontoitlabs.hunter.activity.AddJobsActivity.init(AddJobsActivity.java:107)
            at com.prontoitlabs.hunter.activity.AddJobsActivity.onCreate(AddJobsActivity.java:100)
            at
</code>
this the code being used 

<code>
private void initFAB() {
        ScrollView scrollView = (ScrollView) findViewById(R.id.sv_add_jobs);
        fab = (FloatingActionButton) findViewById(R.id.fab_add_jobs);
        fab.attachToScrollView((ObservableScrollView) scrollView);
    }
</code>

**Comment by iceteahh** [comment]
Use `ObservableScrollView ` instead `ScrollView`

**Comment by makovkastar** [comment]
@iceteahh is right, you should use the ``ObservableScrollView`` from the library (https://github.com/makovkastar/FloatingActionButton/blob/master/library/src/main/java/com/melnykov/fab/ObservableScrollView.java).
